### ISSUE TITLE
Changing zones does not re-initialize the addon

### ISSUE THREAD

**Issue by Sellorio** [Sellorio/mega-macro#101]

**Comment by Sellorio** [comment]
I am unable to reproduce this, Magustar.

What kind of zone change are we talking? i.e. Portals, Flying, Boats, etc.

I tested flying and portal and both didn't have any issues.

**Comment by Magustar** [comment]
Ok just confirmed using Garrison Hearthstone from BFA did trigger all macros to revert to "?"

**Comment by Sellorio** [comment]
I am not able to reproduce this :( Used my hearthstone to get to Void Elf start zone, switched to using native action bars, used garrison hearthstone. No issues throughout.

**Comment by Magustar** [comment]
Hmm just got out of Proving Grounds same thing.  But a reload does correct it.

**Comment by Sellorio** [comment]
Closing for now since I'm not sure what more I can do given it's not happening to me.
