### ISSUE TITLE
Macro icons not displaying correctly

### ISSUE THREAD

**Issue by bmorzos** [Sellorio/mega-macro#102]
I have several macros that do not show the correct icon. Seems like it might be all the same problem.
This is a BM hunter macro.

#showtooltip
/use [mod:ctrl,@cursor]Tar Trap
/stopmacro [mod:ctrl]
/petattack
/use [mod:shift]Bestial Wrath;Kill Command
/use Claw
/use Bite
/use Smack

Outside of mega macro it works like this;
- without any buttons pressed the Kill command icon is displayed
- when pressing shift the Bestial Wrath icon is displayed
-when the control key is pressed the Tar Trap icon is displayed

In Mega Macro:
- without any buttons pressed an icon with 3 claws is displayed (some sort of default im guessing since all my macros have it)
- when pressing shift no change the same 3 claw/default icon
-when the control key is pressed the Tar Trap icon is displayed (this works as expected)

More examples of failing macros:
#showtooltip
/petattack
/cast Counter Shot
/use Claw(Basic Attack)
/use Bite(Basic Attack)
/use Smack(Basic Attack)

#showtooltip Barbed Shot
/petattack
/cast [mod:shift] Multi-Shot;  Barbed Shot
/use Claw
/use Bite
/use Smack

#showtooltip
/petattack
/use 13
/cast Multi-Shot
/use Claw(Basic Attack)
/use Bite(Basic Attack)
/use Smack(Basic Attack)

Thank you for the addon!

**Comment by Sellorio** [comment]
This is intended functionality. The `/petattack` command has an icon in Mega Macro. If you move it to be the last command (or just later) then that will resolve your issue.

**Comment by bmorzos** [comment]
That was it, tyvm
