### ISSUE TITLE
Tooltip Icons not showing on action bars

### ISSUE THREAD

**Issue by LybrialsGit** [Sellorio/mega-macro#106]
Non of the tooltip icons are showing on the action bars

![WoWScrnShot_102520_051448](https://user-images.githubusercontent.com/3900682/97098773-23136d00-1681-11eb-8d49-a99c525447a7.jpg)

**Comment by Sellorio** [comment]
If you select an icon to display, no tooltip will be shown. The tooltip is only shown if the macro's spell/item is used to calculate icon and stuff.

**Comment by LybrialsGit** [comment]
Hi,

I dont need the tooltip to be shown. I need the icon to be shown.
When I use "#showtooltip Cobra Shot" I would expect the cobra shot icon to be shown.
In the macros area of your addon the cobra shot is showing perfectly as you see.
But on the action bar there is only a question mark. No Cobra Shot Icon.

**Comment by Sellorio** [comment]
It should work. Maybe try recreating the macro.

**Comment by LybrialsGit** [comment]
Hi,

yeah I played around a couple of hours before I opened that ticket.
I have tried many different things.
I do not get the icons to show on the action bar.

**Comment by Sellorio** [comment]
Are you able to drag that macro from the Mega Macro UI to your action bar?

**Comment by LybrialsGit** [comment]
Yes

**Comment by LybrialsGit** [comment]
Ok, there must be an incompatibility issue between Mega Macros and the action bars addon im using.
When I disable it, the macro icons are showing perfectly (on default blizzard ui)

**Comment by Sellorio** [comment]
Which addon is that?

**Comment by LybrialsGit** [comment]
Dont worry.

It is a self coded, yet not released action bar addons. But it basically works similar to combarable action bars like bartender, dominos or elvui action bars. Since all of these are working perfectly together with mega macro the problem must be
on my side. I will find and solve the problem.

Thank you for your time!

**Comment by Sellorio** [comment]
I have to manually support those by identifying a way to iterate over all action buttons. For ElvUI and BT4 this is just a matter of getting the active buttons from Lib Action Button. For Dominos and Blizzard UI it's by going over each button by name. I'm guessing you don't use Lib Action Button and have your own button naming convention.

**Comment by LybrialsGit** [comment]
Actually im using Lib Action Button.

**Comment by Sellorio** [comment]
Interesting. Are you not updating the active buttons variable? I'm not _that_ familiar with action button addons heh

**Comment by LybrialsGit** [comment]
The only API function from Lib Action Button which im using is _CreateButton_ which is creating a button and adding it to the button registry of Lib Action Button

**Comment by Sellorio** [comment]
This line iterates over registered LAB buttons:
https://github.com/Sellorio/mega-macro/blob/0058493b2e529c6cc18ab60e8ec5796d16604fdf/src/engine/mega-macro-action-bar-engine.lua#L307
