### ISSUE TITLE
Addon Action Blocked error message

### ISSUE THREAD

**Issue by KestrelWild** [Sellorio/mega-macro#110]
Getting this error in combat quite often:

1x [ADDON_ACTION_BLOCKED] AddOn 'MegaMacro' tried to call the protected function 'MegaMacroClicky91:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@MegaMacro\src/engine/mega-macro-engine.lua"]:225: in function <...ceMegaMacro\src/engine/mega-macro-engine.lua:220>
[string "@MegaMacro\src/engine/mega-macro-engine.lua"]:242: in function <...ceMegaMacro\src/engine/mega-macro-engine.lua:239>
[string "@MegaMacro\src/engine/mega-macro-engine.lua"]:389: in function `OnSpecializationChanged'
[string "@MegaMacro\src/main.lua"]:60: in function <MegaMacro\src/main.lua:47>

**Comment by Sellorio** [comment]
Fixed already in #108. Not released yet.
