### ISSUE TITLE
LUA error: Fresh install 

### ISSUE THREAD

**Issue by Fraktyl** [Sellorio/mega-macro#116]
Getting the following LUA error when I log in/reload.  This is on version 1.5.3

`4x ...s\MegaMacro\src/engine/mega-macro-icon-evaluator.lua:243: Usage: SetMacroItem(macro, item [,target])
[string "=[C]"]: in function `SetMacroItem'
[string "@MegaMacro\src/engine/mega-macro-icon-evaluator.lua"]:243: in function <...s\MegaMacro\src/engine/mega-macro-icon-evaluator.lua:209>
[string "@MegaMacro\src/engine/mega-macro-icon-evaluator.lua"]:259: in function <...s\MegaMacro\src/engine/mega-macro-icon-evaluator.lua:253>
[string "@MegaMacro\src/engine/mega-macro-icon-evaluator.lua"]:307: in function `Update'
[string "@MegaMacro\src/main.lua"]:15: in function <MegaMacro\src/main.lua:12>

Locals:
(*temporary) = 119
(*temporary) = nil
(*temporary) = nil`

This is on all characters and is the exact same error for all.  Not sure if this is on my end.

**Comment by Sellorio** [comment]
Which macro is triggering this?

**Comment by Fraktyl** [comment]
It was a trinket macro:
#showtooltip
/use [mod:shift]13;14

I rewrote it exactly like it was, and the errors are gone now.  Not sure why the first time caused it to throw errors.

**Comment by Sellorio** [comment]
Fixed in latest release.
