### ISSUE TITLE
Macros being removed from bars.

### ISSUE THREAD

**Issue by griddark** [Sellorio/mega-macro#118]
I haven't figured out exactly when, or why, but I can have macros removed from the action bar.

Sometimes it's on reload, other times logging from 1 character to the other. It isn't throwing out any errors, so not sure why it's happening.

**Comment by Sellorio** [comment]
I don't know what that could be.

When leaving a Torghast instance after changing spec, blizzard keeps the action bar layout from the spec you changed to and reverts your spec. This means that any abilities and assignments not common to both are removed. This doesn't sound like what you're talking about though.

The other issue I know about is that when blizzard cloud sync macros they sometimes just screw up and that will result in Mega Macro recreating a few macros - thus breaking the action bar. But that shouldn't happen on /reload. Only on restart and maybe when switching characters.

I guess continue monitoring and let me know.

**Comment by griddark** [comment]
So I can reproduce the issue every time, it's just on fresh log in of a character, the macro's don't stay in the place I put them on the bars. I'm going to turn off all the other addon's and test to see if something else is causing it or if it's happening with just Mega Macro.

**Comment by griddark** [comment]
Just deleted every macro on every character, and removed all the general macro's made by mega macro, deleted all references to mega macro from the WTF folder, and created a fresh macro, it removed from the bars on reload. 
This happens regardless of if I'm running other addon's or not. 
Happens on a completely fresh character also, /reload and the macro is no longer in the bar.

**Comment by Sellorio** [comment]
That's pretty impressive

**Comment by Sellorio** [comment]
I'm not trying to be mean or anything but its really unlikely that everything you just said is accurate.

My only idea at this point is that another addon is interfering. If you want, please disable/temporarily delete all other addons and reset Mega Macro's data as well as emptying (not deleting) your macro-cache.txt files.

**Comment by davidhdez** [comment]
Same boat, it's happening all the time with many characters

**Comment by Roskalov** [comment]
I had that issue too. Try giving your macros names (I use a dot ["."] for all) that you will not encounter this

**Comment by Sellorio** [comment]
If that fixes it, I can probably commit a fix. Simply make it so if people give a blank name, i'll use " " which is what I used back in the old UI when I didn't want a label.
