### ISSUE TITLE
Attempt to call protected function 'original()' when dragging macro out of macro window

### ISSUE THREAD

**Issue by nathanpaulyoung** [Sellorio/mega-macro#119]
`1x [ADDON_ACTION_BLOCKED] AddOn 'MegaMacro' tried to call the protected function 'original()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function 'original'
[string "@MegaMacro\src/engine/mega-macro-engine.lua"]:273: in function <...ceMegaMacro\src/engine/mega-macro-engine.lua:264>
[string "@MegaMacro\src/engine/mega-macro-engine.lua"]:324: in function 'PickupMacro'
[string "@MegaMacro\src/windows/mega-macro.window.lua"]:307: in function <...eMegaMacro\src/windows/mega-macro.window.lua:303>
[string "@MegaMacro\src/windows/mega-macro.window.lua"]:538: in function 'MegaMacro_MacroButton_OnDragStart'
[string "*:OnDragStart"]:1: in function <[string "*:OnDragStart"]:1>`

Made macro, then dragged onto cat bar, used it, switched to bear, dragged onto bar, used it, left form, dragged out of window, error. Macro contained the following:

`#showtooltip
/use [@mouseover,harm,form:1/2][@mouseovertarget,harm,form:1/2][harm,form:1/2][@targettarget,harm,form:1/2][form:1/2]Wild Charge
/use [@mouseover,help][@target,help][@targettarget,help][]Wild Charge`

**Comment by Sellorio** [comment]
Where you in combat? You can't pickup macros in combat.

**Comment by nathanpaulyoung** [comment]
Not sure, but it's possible, as I was at the Target Dummies in Heart of the Forest. It's likely that I charged one to test my macro which put me in combat.

That explains the issue. Maybe there's a way to more gracefully handle this issue, though? It required me to reload my UI to resume use of the addon.

**Comment by Sellorio** [comment]
That's weird. It shouldn't require a reload. I'll fix that :)
