### ISSUE TITLE
Other Addons cant create Macros because mega-macro occupies all macro slots.

### ISSUE THREAD

**Issue by Drathal** [Sellorio/mega-macro#123]
Example: Im using Azeroth Auto Pilot and get an Info that it cannot create a Macto because my global Macro Space is full.

Is that because i use 'mega-macro' in a wrong way? 

Btw: Great work i really love this Addon :)

**Comment by Sellorio** [comment]
Alas it is what it is. MM uses all macro slots, to do otherwise would be challenging.

**Comment by Drathal** [comment]
Pk, Thanks for the Answer :)
