### ISSUE TITLE
[Question/Feature Request] Is there / can there be an analogue to /run MacroFrameText:Insert("") ?

### ISSUE THREAD

**Issue by nathanpaulyoung** [Sellorio/mega-macro#124]
This macro allows one to send item links into the default macro pane after clicking into the macro where you want the text to be inserted and then pressing escape to shift back to global focus.

`/run MacroFrameText:Insert("")`

Is there something equivalent for the edit frame in Mega Macro, and if not, can there be?

**Comment by Sellorio** [comment]
Yup, use `MegaMacro_FrameText` instead of `MacroFrameText`.

**Comment by nathanpaulyoung** [comment]
Excellent! Thank you!
