### ISSUE TITLE
Buttonforge addon conflict

### ISSUE THREAD

**Issue by Erfar** [Sellorio/mega-macro#140]
![Screenshot_7](https://user-images.githubusercontent.com/77942879/111326813-896f4b00-8675-11eb-903c-0f8cca8dca88.png)
Meet issue with puting macro on buttonforge pannel - macro icon is not revealing

**Comment by LDARBY** [comment]
I have the same issue with the icons.

**Comment by sellorio2** [comment]
There are no intentions to add support for buttonforge. All I can suggest is reachinig out to buttonforge to see if they want to add Mega Macro support.
