### ISSUE TITLE
Can't link guild invite link

### ISSUE THREAD

**Issue by MrWizard516** [Sellorio/mega-macro#143]
I need to be able to make a guild recruitment macro that contains my guild link. The issue is that the SHIFT+CLICK doesn't work. Any idea if or when you will have this feature working?

**Comment by Sellorio** [comment]
Similarly to the old macro UI, you need to put the link in chat and have a command insert it into the macro text field.

Exact steps are linking into chat, then wrapping the link in the code as shown below. Then when you press enter it gets inserted into the macro text field. You need to have the macro UI open to the macro you want to edit for this to work.

```
/script MegaMacro_FrameText:Insert("[Eternal Fire]")
```

For native macro system (for reference)

```
/script MacroFrameText:Insert("[Eternal Fire]")
```

**Comment by MrWizard516** [comment]
Thank you for your fast response. I tried it and it inserts what looks like a link but it doesn't actually do anything

**Comment by Sellorio** [comment]
Glad I could help :)
