### ISSUE TITLE
The is a great addon, Is it still being maintained?

### ISSUE THREAD

**Issue by MrWizard516** [Sellorio/mega-macro#146]
I have noticed that the developer has not responded to many tickets for quite some time now. Is this project still be maintained and developed? There are very important issues that need to be addressed.

**Comment by Sellorio** [comment]
I responded a few minutes ago to one of the issues. This mod is no longer being maintained by me. If you feel the itch to dabble, I am happy to support others contributing to the mod to perform ongoing maintenance and feature development.

FYI, this is not a cause to raise Issues as issues are meant to relate to the delivered item.
