### ISSUE TITLE
New 'known:' and 'noknown:' conditionals

### ISSUE THREAD

**Issue by Kaaasper** [Sellorio/mega-macro#199]
In dragonflight two new macro conditionals were added to check if a talent was learned or not. Their use is outlined in [this wowhead post.](https://www.wowhead.com/news/dragonflight-pre-expansion-phase-2-updates-new-macro-conditional-for-known-329834)

I tried simply adding them to the Conditionals list locally which makes the macros work, but as far as I can tell none of the parsing functions allow for spaces. This means words beyond the first when a talent's name is used in the conditional will appear red in the macro editor. It is not a huge bother for someone familiar with the issue, but I imagine a clean implementation in the official release will require someone takes a look at the parsing as well.

**Comment by aurelion314** [comment]
This previously went live in #195 and a bug fix went live with #188. This can be closed. @Sellorio
