### ISSUE TITLE
[10.2] Macro icon doesn't update with modifyers while on combat

### ISSUE THREAD

**Issue by Dabeuliou** [Sellorio/mega-macro#208]
Hello,

I've noticed that since the 10.2 update, my macro using modifyers doen't show the correct spell icon while i'm in combat. IT seems that it's frozen as soon as I enter a fight.

For instance, this macro:
```
#showtooltip
/cast [mod:shift] Déchirure;[known:Colère primitive,mod:alt] Colère primitive; Griffure
```
It's supposed to show the "Colère primitive" icon when i push ALT, it works out of combat, but it doesn't change in combat, the "Griffure" stays if it was the one displayed when the fight started.
I've tried to remove all the addons excepted MegaMacro and it still doesn't work, hence my ticket here.

Btw, thanks for this excellent addon!

**Comment by Dabeuliou** [comment]
I also notice that the tooltips don't show, only the macro ID is shown.

**Comment by Dabeuliou** [comment]
Following the today's update, I added unique names to the macros as suggested and now the icons are changing during fights again...!

**Comment by Sellorio** [comment]
Happy days! :)

**Comment by Dabeuliou** [comment]
Hoping than when Blizzard corrects the issue on the function you use, it will be possible agin to use "unnamed" macros.
