### ISSUE TITLE
11.0.0 Prepatch - New error being spammed, doesn't appear to affect functionality

### ISSUE THREAD

**Issue by morgan35543** [Sellorio/mega-macro#220]
This new UI error is happening 10s of times per second. Macros appear to function perfectly fine however the chat box is filled with warnings about addon errors.

![image](https://github.com/user-attachments/assets/0730dba5-268e-4fea-9624-d49f708a94e8)

**Comment by Sellorio** [comment]
Did you update to the latest version? An update came out a few hours ago to the addon that should have fixed all that.

**Comment by morgan35543** [comment]
ohh ok, i'll download it from github as it doesn't seem to have pushed to the curseforge app yet

thanks for keeping this addon alive!

![image](https://github.com/user-attachments/assets/4ee3a5d6-8d4b-4d5c-8a31-f2a3ee85169e)
