### ISSUE TITLE
Macros don't track spell charges

### ISSUE THREAD

**Issue by Buckmon** [Sellorio/mega-macro#223]
My holy shock mouseover macro doesn't track charges or recharge rate.
C_Spell.GetSpellCharges() got updated in 11.0 and returns a SpellChargeInfo table instead of a tuple.
https://warcraft.wiki.gg/wiki/API_C_Spell.GetSpellCharges

**Comment by bpapuni** [comment]
Believe this is fixed in version 1.6.2. I tested a mouseover macro for Holy Shock and am able to see charges and recharge rate.
