### ISSUE TITLE
Unable to move macros from MegaMacro to bars.

### ISSUE THREAD

**Issue by kamari0** [Sellorio/mega-macro#59]
Disabled all addons and am only using Mega Macro I am unable to move any macros to my character bars.

Message: Interface\AddOns\MegaMacro\src/mega-macro-engine.lua:11: bad argument #1 to 'sub' (string expected, got nil)
Time: Thu Oct  8 13:23:39 2020
Count: 1
Stack: Interface\AddOns\MegaMacro\src/mega-macro-engine.lua:11: bad argument #1 to 'sub' (string expected, got nil)
[string "=[C]"]: in function `sub'
[string "@Interface\AddOns\MegaMacro\src/mega-macro-engine.lua"]:11: in function <Interface\AddOns\MegaMacro\src/mega-macro-engine.lua:10>
[string "@Interface\AddOns\MegaMacro\src/mega-macro-engine.lua"]:139: in function <Interface\AddOns\MegaMacro\src/mega-macro-engine.lua:133>
[string "@Interface\AddOns\MegaMacro\src/mega-macro-engine.lua"]:272: in function `SafeInitialize'
[string "@Interface\AddOns\MegaMacro\src/main.lua"]:36: in function <Interface\AddOns\MegaMacro\src/main.lua:16>
[string "@Interface\AddOns\MegaMacro\src/main.lua"]:44: in function <Interface\AddOns\MegaMacro\src/main.lua:42>

Locals: (*temporary) = nil
(*temporary) = 2
(*temporary) = 4
(*temporary) = "string expected, got nil"

**Comment by Sellorio** [comment]
Thanks for raising this :) My commit should fix that specific error although I'm surprised it happened. It requires a macro to have null/nil code. Hope this solves it for you!

I'm currently working on another rewrite of the action bar logic which hopefully won't take too long. Your fix will be in the next release.
