### ISSUE TITLE
Can't drag macros to bar

### ISSUE THREAD

**Issue by Londirin** [Sellorio/mega-macro#61]
See title. Love the addon - exactly what I'm looking for - how can I help?

**Comment by Sellorio** [comment]
I'm curious how you'll fare with the development version. I suggest downloading the contents of this repo and using that in your addons folder. Unfortunately I can't reproduce these kinds of issues on my end :(

**Comment by Londirin** [comment]
Brand new to github - I'm going to try deleting all the "new" macros it made. I bit ago I did the whole set addon txtfile to false, etc. It made a bunch of macros in the "old" macro tab, and when you do /m it pulls up both megamacro's tab and the old tab.

**Comment by Londirin** [comment]
If I replace it with the one from your repo, it will delete all my current macros right?

**Comment by Sellorio** [comment]
Yeah so if the auto-import can't complete because you have a lot of character-specific or global macros, you won't have full functionality until you manually copy across the macros you want and delete the old ones.

**Comment by Londirin** [comment]
Downloaded and updated the addon to the one in your repo, did not fix the issue :/ The "General Macros" tab of the "old" /m is now repopulated with all the stuff I just deleted.

**Comment by Londirin** [comment]
Was working fine the day before yesterday

**Comment by Sellorio** [comment]
I'm having a hard time understanding what your experiencing from your comments. If /m opens both new and old macro UI, that means import is not complete and you'll have to copy across your macros to the new ui and delete your macros from the old UI. If the import was complete for Global macros then you'll see every macro slot filled with macros that just click buttons.

**Comment by Londirin** [comment]
Yes every macro in the "old" macro tab is filled with "click" macros

**Comment by Londirin** [comment]
Want to join my zoom real fast just so you can get an idea? I can share my screen

**Comment by Sellorio** [comment]
I don't use Zoom but I'm happy to a discord direct call

**Comment by Sellorio** [comment]
Sellorio#9460

**Comment by Londirin** [comment]
sweet
sec

**Comment by Londirin** [comment]
I sent a thing, I am Lion

**Comment by Sellorio** [comment]
For anyone else visiting this page, the issue was some kind of failure in the initial import/initialize of the addon for character specific macros. The solution was to delete the `MegaMacro.lua` on the character where the issue was happening so that the addon would reinitialize the character macros.
