### ISSUE TITLE
Specific macro slots cannot be dragged to the action bar

### ISSUE THREAD

**Issue by kamari0** [Sellorio/mega-macro#67]
I've found that there are macros that are unable to be moved from the macro menu:
Class: 1st and 5th macro created.
Spec: 29th macro created.

https://streamable.com/d4jmh1

I've tested this on multiple characters. I'm using the latest commit. 

Whenever you delete the "unmovable" macro it becomes the next one created.

I'm currently getting around this by leaving the "unmovable" macros filled, then deleting them at the end. 

https://imgur.com/oOPZij0

**Comment by Sellorio** [comment]
Hi @kamari0, It sounds like some of the macro stubs have been messed around with. Probably by addons. Could you send me your global macro data? It's at `C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\{YourAccount}\macros-cache.txt`.

**Comment by kamari0** [comment]
[macros-cache.txt](https://github.com/Sellorio/mega-macro/files/5368914/macros-cache.txt)

**Comment by Sellorio** [comment]
Hmm those look fine based on a quick skim.

The only thing I can suggest is a really technical solution:

1. Empty out your macro-cache.txt (make it a blank file).
2. Update `C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\{YourAccount}\SavedVariables\MegaMacro.lua` and change `["Activated"] = true,` to `["Activated"] = false,`.

This will cause it to reinitialize the global macros which should fix the issue. You'll probably have to re-set your action bars once you do this. Probably worth backing up your WTF folder before hand so you can easily revert it all if that doesn't work.
