### ISSUE TITLE
Druid form action bar paging load cached icons

### ISSUE THREAD

**Issue by ghost0doctor** [Sellorio/mega-macro#75]
I can setup macros and drag to each form's action bar through the primary action bar.  However, when I change druid form, the icons from the first loaded form appear.  The macro itself works, but the icons for all abilities are from the original form.

I initially saw this where I started in caster form and saw all caster macros.  When I shift to bear form I still see all caster icons. 

I tested the behavior by shifting to bear form and reloading.  All bear icons then appeared correctly, but when I shifted to caster form the bear icons still appeared.  

It seems like this may be related to icon caching and icons not updating with druid form shifts through action bar paging.

**Comment by Sellorio** [comment]
Ah yes. I don't page my action bars based on form. I just have macros that are form-aware as needed so I never ran into this issue. Is this using Bartender or native ui?

**Comment by ghost0doctor** [comment]
Elvui actually.  But I tested it with Bartender and native ui as well and the issue occurs on all three action bar versions.

**Comment by Sellorio** [comment]
I can't reproduce this issue. Make sure you are on the latest version. Also if you put mod:alt modifiers in a macro, does it update the icon correctly?

**Comment by Arthonn** [comment]
Hey Sellorio, I've captured my screen so you can see the issue

https://imgur.com/a/t0eFYHj

This is made with only Mega and Elvui on. IF I disable Elvui, the issue doesn't occur. I don't have Bartender myself, but if the user above runs into the issue with it, there might be a small conflict with action bar addons? Hope this helps.

**Comment by Sellorio** [comment]
I have found the issue. Just some minor side-issues I still gotta fix - like the OOM indicator being visible if switching form and the slot is empty after doing so (since nothing updates it)
