### ISSUE TITLE
Other addons not seeing keybinds for macros

### ISSUE THREAD

**Issue by KestrelWild** [Sellorio/mega-macro#76]
Playing around with Hekili and Hero Rotation. Before pre-patch they showed the keybindings of mega macros I had slotted on ability bars. Since pre-patch they no longer do.

With spell dragged straight from spellbook (this is how it looked before prepatch using mega macros)

![2020-10-15 15_38_13-World of Warcraft](https://user-images.githubusercontent.com/10617817/96177880-8c1a1880-0efc-11eb-82c4-d1a1516773bd.png)

With mega macro after prepatch

![2020-10-15 15_34_29-World of Warcraft](https://user-images.githubusercontent.com/10617817/96177911-9a683480-0efc-11eb-9c64-cd795df869fa.png)

**Comment by Sellorio** [comment]
Support for addons other than BT4 and ElvUI do not exist. Having said that, I will try to make a change in the next update and you'll need to tell me if that works.

**Comment by KestrelWild** [comment]
No luck unfortunately. I wonder why it was working before pre-patch. Odd! Thanks for giving it a shot.

**Comment by KestrelWild** [comment]
Whoa, I take it back! I left Org where I was playing around on Training Dummy and suddenly they showed up. Went back to Org and they are still there. No idea what's going on there, but they seem to be back.
