### ISSUE TITLE
Intermittent Error

### ISSUE THREAD

**Issue by MetalHeadSeven** [Sellorio/mega-macro#81]
1x [ADDON_ACTION_BLOCKED] AddOn 'MegaMacro' tried to call the protected function 'MultiBarBottomLeftButton4:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:348: in function `Update'
[string "@FrameXML\ActionButton.lua"]:328: in function <FrameXML\ActionButton.lua:323>
[string "=[C]"]: ?
[string "@FrameXML\SecureHandlers.lua"]:266: in function <FrameXML\SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML\SecureHandlers.lua"]:430: in function <FrameXML\SecureHandlers.lua:417>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\SecureHandlers.lua"]:310: in function <FrameXML\SecureHandlers.lua:306>
[string "=(tail call)"]: ?

**Comment by Sellorio** [comment]
I can't reproduce this. Any additional info you can give as to when it happens would help. Also make sure you are running the latest release version.

What addon are you using for your action bars (if any)?

**Comment by MetalHeadSeven** [comment]
I'm using version 1.3.2.  I just saw your comment that Dominos is not supported so I think that may be the problem.

**Comment by Sellorio** [comment]
Yeah sorry. #79 is there to track the task to add Dominos support. I probably won't get around to it any time soon. If you have the inclination you are welcome to make a pull request.

**Comment by MetalHeadSeven** [comment]
No problem.  I really like your addon so I'll just uninstall until you eventually add Dominos support.
