### ISSUE TITLE
General Macros Won't Delete

### ISSUE THREAD

**Issue by Magustar** [Sellorio/mega-macro#88]
All macro pages are full of stub macros.  Deleted macros but they reappear after login.  General macros in made in Mega Macro are not correct.  They have the right image from #showtooltip for the macro I ask for but they won't work when the button is pushed and their label is for a different macro.
![image](https://user-images.githubusercontent.com/73049124/96358583-73f9f300-10ce-11eb-96e6-8d692133150e.png)

**Comment by Sellorio** [comment]
This is the intended functionality. If you delete the stub macros you will break the addon's behaviour. You're lucky that I've enhanced the initialization logic in 1.3.3+ to be more resilient.

You shouldn't be using the old macro interface at all. Only the new one.
