### ISSUE TITLE
Macro placed on bar is not the macro selected

### ISSUE THREAD

**Issue by Magustar** [Sellorio/mega-macro#89]
Macros placed on bar from Mega Macro are not the macro that was selected.
![image](https://user-images.githubusercontent.com/73049124/96358744-47df7180-10d0-11eb-9a8a-8fa9968ec635.png)

**Comment by Sellorio** [comment]
I can't reproduce this. Please provide more info. What is "jewe..." macro? is it from the new UI or the old one? Is it something you wrote or is it created by an addon?

**Comment by Magustar** [comment]
It's a macro I wrote for Jewelcrafting.  It was imported from the old UI.

**Comment by Magustar** [comment]
Jewelcrafting macro contains...
![image](https://user-images.githubusercontent.com/73049124/96358881-9c372100-10d1-11eb-9920-ddbb047a635b.png)

What should be there is the Hearthstone macro...
![image](https://user-images.githubusercontent.com/73049124/96358892-b670ff00-10d1-11eb-9746-2ff1da39aff2.png)

**Comment by Sellorio** [comment]
Try recreating the macros and see if that fixes it I guess. Also try /reload. This is the first I've heard of this issue and I can't reproduce it unfortunately.

**Comment by Magustar** [comment]
Recreating macros did work.
