### ISSUE TITLE
Constant LUA errors caused by Dimensional Ripper macros

### ISSUE THREAD

**Issue by Magustar** [Sellorio/mega-macro#93]
Great mod exactly what I've been looking for but I'm getting crazy numbers of LUA errors.  Not sure where the conflict is but wanted to post it to make you aware.
![image](https://user-images.githubusercontent.com/73049124/96378290-93d1fb00-1150-11eb-8a6d-868193bffe2d.png)

**Comment by Magustar** [comment]
Looks like this may be connected to macro using Goblin Teleporters;

#showtooltip
/cast [mod:shift] Dimensional Ripper - Area 52; Dimensional Ripper - Everlook

When recreating the macro the tooltip won't update but the macro works but I can see the LUA errors piling up when I place this on the toolbar

**Comment by Sellorio** [comment]
I made a fix that should fix it. I don't have engineering on anyone so I can't really test it unfortunately.
